//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyProduct("Cake.SqlServer")]
[assembly: AssemblyVersion("1.7.1.0")]
[assembly: AssemblyFileVersion("1.7.1.0")]
[assembly: AssemblyInformationalVersion("1.7.1-bugfix-ilmerge.1+9.Branch.bugfix/ilmerge.Sha.a67a2f9632d9f97c24ced4da8dcf7d80742e74e2")]
[assembly: AssemblyCopyright("Copyright (c) 2016 - 2016 AMV Software")]

[assembly: InternalsVisibleTo("Tests")]